require(shinysky)
library(RColorBrewer)
library(GISTools)
library(shinythemes)
library("klaR")
library("caret")
options(shiny.maxRequestSize=30*1024^2)
clfs = list("Naive Bayes" = "nb","Logistic Regression" = "logreg")